<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <NoWarn>1701;1702;1591;NETSDK1138</NoWarn>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<IsPublishable>false</IsPublishable>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sandbox.Bind\Sandbox.Bind.csproj" />
    <ProjectReference Include="..\Sandbox.Generator\Sandbox.Generator.csproj" />
    <ProjectReference Include="..\Sandbox.System\Sandbox.System.csproj" />
    <ProjectReference Include="..\Sandbox.Engine\Sandbox.Engine.csproj" />
    <ProjectReference Include="..\Sandbox.SceneRenderer\Sandbox.SceneRenderer.csproj" />
  </ItemGroup>

</Project>

