using Microsoft.CodeAnalysis;
using System;

namespace Sandbox.Generator;

/// <summary>
/// The Razor SDK compiles a project's .razor files - this fills in the sandbox-specific bits
/// its generator doesn't know about. Each component gets the class file location the runtime
/// uses to find its .razor.scss (relative to the SandboxRazorRoot msbuild property), and the
/// render tree checksum that marks it as having a razor tree at all.
/// </summary>
[Generator]
public class RazorGenerator : IIncrementalGenerator
{
	public void Initialize( IncrementalGeneratorInitializationContext context )
	{
		var razorFiles = context.AdditionalTextsProvider
			.Where( static x => x.Path.EndsWith( ".razor", StringComparison.OrdinalIgnoreCase ) );

		var withOptions = razorFiles.Combine( context.AnalyzerConfigOptionsProvider );

		context.RegisterSourceOutput( withOptions, static ( spc, pair ) =>
		{
			var file = pair.Left;
			var options = pair.Right.GlobalOptions;

			options.TryGetValue( "build_property.projectdir", out var projectDir );
			options.TryGetValue( "build_property.rootnamespace", out var rootNamespace );
			options.TryGetValue( "build_property.SandboxRazorRoot", out var razorRoot );

			var text = file.GetText( spc.CancellationToken )?.ToString();
			if ( text is null ) return;

			var localPath = LocalPath( file.Path, projectDir, razorRoot );
			var className = System.IO.Path.GetFileNameWithoutExtension( file.Path );
			var ns = FindNamespace( text ) ?? DeriveNamespace( localPath, rootNamespace );

			if ( string.IsNullOrEmpty( ns ) ) return;

			var source = $$"""
				// <auto-generated />
				namespace {{ns}}
				{
					[global::Sandbox.Internal.ClassFileLocation( "{{localPath}}" )]
					public partial class {{className}}
					{
						protected override string GetRenderTreeChecksum() => "{{Checksum( text )}}";
					}
				}
				""";

			spc.AddSource( $"{className}_{(uint)localPath.GetHashCode():x8}.sandbox.g.cs", source );
		} );
	}

	/// <summary>
	/// The path the file has inside the mounted filesystem the app will serve it from.
	/// </summary>
	static string LocalPath( string path, string projectDir, string razorRoot )
	{
		var full = path.Replace( '\\', '/' );

		if ( !string.IsNullOrEmpty( projectDir ) )
		{
			var root = projectDir.Replace( '\\', '/' ).TrimEnd( '/' );

			if ( !string.IsNullOrEmpty( razorRoot ) )
				root = $"{root}/{razorRoot.Replace( '\\', '/' ).Trim( '/' )}";

			if ( full.StartsWith( root, StringComparison.OrdinalIgnoreCase ) )
				full = full.Substring( root.Length );
		}

		return "/" + full.TrimStart( '/' );
	}

	/// <summary>
	/// The component's namespace, from its own @namespace directive.
	/// </summary>
	static string FindNamespace( string text )
	{
		var match = System.Text.RegularExpressions.Regex.Match( text, @"^\s*@namespace\s+([\w\.]+)", System.Text.RegularExpressions.RegexOptions.Multiline );
		return match.Success ? match.Groups[1].Value : null;
	}

	/// <summary>
	/// The namespace the Razor SDK derives when there's no directive - root plus folders.
	/// </summary>
	static string DeriveNamespace( string localPath, string rootNamespace )
	{
		if ( string.IsNullOrEmpty( rootNamespace ) ) return null;

		var ns = rootNamespace;
		var directory = System.IO.Path.GetDirectoryName( localPath )?.Replace( '\\', '/' ) ?? "";

		foreach ( var folder in directory.Split( new[] { '/' }, StringSplitOptions.RemoveEmptyEntries ) )
		{
			if ( char.IsDigit( folder[0] ) || folder.Contains( " " ) || folder.Contains( "-" ) || folder.Contains( "." ) ) continue;
			ns += "." + folder;
		}

		return ns;
	}

	/// <summary>
	/// Changes when the markup changes, so the runtime knows to rebuild the tree on hotload.
	/// </summary>
	static string Checksum( string text )
	{
		using var sha = System.Security.Cryptography.SHA256.Create();
		var hash = sha.ComputeHash( System.Text.Encoding.UTF8.GetBytes( text ) );
		return BitConverter.ToString( hash, 0, 8 ).Replace( "-", "" ).ToLowerInvariant();
	}
}
