<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<NoWarn>1701;1702;1591;NETSDK1138</NoWarn>
		<DebugType>full</DebugType>
		<LangVersion>14</LangVersion>
		<EnforceExtendedAnalyzerRules>false</EnforceExtendedAnalyzerRules>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.12.0-beta1.25218.8" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Microsoft.AspNetCore.Razor.Language\ComponentResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ComponentResources.resx</DependentUpon>
		</Compile>
		<Compile Update="Microsoft.AspNetCore.Razor.Language\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Microsoft.AspNetCore.Razor.Language\ComponentResources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>ComponentResources.Designer.cs</LastGenOutput>
			<CustomToolNamespace>Microsoft.AspNetCore.Razor.Language</CustomToolNamespace>
		</EmbeddedResource>
		<EmbeddedResource Update="Microsoft.AspNetCore.Razor.Language\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
			<CustomToolNamespace>Microsoft.AspNetCore.Razor.Language</CustomToolNamespace>
		</EmbeddedResource>
	</ItemGroup></Project>
