// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGAbsolutePositionTest.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGAbsolutePositionTest.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class AbsolutePositionTest : FlexFixtureBase
{
	[TestMethod]
	public void absolute_layout_width_height_start_top()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Start, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_width_height_left_auto_right()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Auto );
		root_child0.Style.SetPosition( Edge.Right, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_width_height_left_right_auto()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.Right, StyleLength.Auto );
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_width_height_left_auto_right_auto()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Auto );
		root_child0.Style.SetPosition( Edge.Right, StyleLength.Auto );
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 90, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_width_height_end_bottom()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.End, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_start_top_end_bottom()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Start, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.End, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.Bottom, StyleLength.Points( 10 ) );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_width_height_start_top_end_bottom()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Start, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.End, StyleLength.Points( 10 ) );
		root_child0.Style.SetPosition( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void do_not_clamp_height_of_absolute_node_to_height_of_its_overflow_hidden_parent()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Overflow = Overflow.Hidden;
		root.Style.Width = StyleLength.Points( 50 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Start, StyleLength.Points( 0 ) );
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Points( 0 ) );
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.Width = StyleLength.Points( 100 );
		root_child0_child0.Style.Height = StyleLength.Points( 100 );
		root_child0.InsertChild( root_child0_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( -50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_within_border()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetMargin( Edge.Left, StyleLength.Points( 10 ) );
		root.Style.SetMargin( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.SetMargin( Edge.Right, StyleLength.Points( 10 ) );
		root.Style.SetMargin( Edge.Bottom, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Left, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Right, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Bottom, StyleLength.Points( 10 ) );
		root.Style.SetBorder( Edge.Left, StyleLength.Points( 10 ) );
		root.Style.SetBorder( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.SetBorder( Edge.Right, StyleLength.Points( 10 ) );
		root.Style.SetBorder( Edge.Bottom, StyleLength.Points( 10 ) );
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Points( 0 ) );
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Points( 0 ) );
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.PositionType = PositionType.Absolute;
		root_child1.Style.SetPosition( Edge.Right, StyleLength.Points( 0 ) );
		root_child1.Style.SetPosition( Edge.Bottom, StyleLength.Points( 0 ) );
		root_child1.Style.Width = StyleLength.Points( 50 );
		root_child1.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.PositionType = PositionType.Absolute;
		root_child2.Style.SetPosition( Edge.Left, StyleLength.Points( 0 ) );
		root_child2.Style.SetPosition( Edge.Top, StyleLength.Points( 0 ) );
		root_child2.Style.SetMargin( Edge.Left, StyleLength.Points( 10 ) );
		root_child2.Style.SetMargin( Edge.Top, StyleLength.Points( 10 ) );
		root_child2.Style.SetMargin( Edge.Right, StyleLength.Points( 10 ) );
		root_child2.Style.SetMargin( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child2.Style.Width = StyleLength.Points( 50 );
		root_child2.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child2, 2 );

		var root_child3 = CreateNode();
		root_child3.Style.PositionType = PositionType.Absolute;
		root_child3.Style.SetPosition( Edge.Right, StyleLength.Points( 0 ) );
		root_child3.Style.SetPosition( Edge.Bottom, StyleLength.Points( 0 ) );
		root_child3.Style.SetMargin( Edge.Left, StyleLength.Points( 10 ) );
		root_child3.Style.SetMargin( Edge.Top, StyleLength.Points( 10 ) );
		root_child3.Style.SetMargin( Edge.Right, StyleLength.Points( 10 ) );
		root_child3.Style.SetMargin( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child3.Style.Width = StyleLength.Points( 50 );
		root_child3.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child3, 3 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 10, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child3, true ).Left, "root_child3.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child3, true ).Top, "root_child3.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child3, true ).Width, "root_child3.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child3, true ).Height, "root_child3.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 10, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child3, true ).Left, "root_child3.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child3, true ).Top, "root_child3.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child3, true ).Width, "root_child3.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child3, true ).Height, "root_child3.Height" );
	}

	[TestMethod]
	public void absolute_layout_align_items_and_justify_content_center()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.AlignItems = Align.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_align_items_and_justify_content_flex_end()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.FlexEnd;
		root.Style.AlignItems = Align.FlexEnd;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_justify_content_center()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_align_items_center()
	{
		var root = CreateNode();
		root.Style.AlignItems = Align.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_align_items_center_on_child_only()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.AlignSelf = Align.Center;
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_align_items_and_justify_content_center_and_top_position()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.AlignItems = Align.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_align_items_and_justify_content_center_and_bottom_position()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.AlignItems = Align.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_align_items_and_justify_content_center_and_left_position()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.AlignItems = Align.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Points( 5 ) );
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 5, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 5, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_align_items_and_justify_content_center_and_right_position()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.AlignItems = Align.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexGrow = 1;
		root.Style.Width = StyleLength.Points( 110 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Right, StyleLength.Points( 5 ) );
		root_child0.Style.Width = StyleLength.Points( 60 );
		root_child0.Style.Height = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 45, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 110, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 45, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void position_root_with_rtl_should_position_withoutdirection()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPosition( Edge.Left, StyleLength.Points( 72 ) );
		root.Style.Width = StyleLength.Points( 52 );
		root.Style.Height = StyleLength.Points( 52 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 72, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 52, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 52, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 72, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 52, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 52, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );
	}

	[TestMethod]
	public void absolute_layout_percentage_bottom_based_on_parent_height()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Percent( 50 ) );
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.PositionType = PositionType.Absolute;
		root_child1.Style.SetPosition( Edge.Bottom, StyleLength.Percent( 50 ) );
		root_child1.Style.Width = StyleLength.Points( 10 );
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.PositionType = PositionType.Absolute;
		root_child2.Style.SetPosition( Edge.Top, StyleLength.Percent( 10 ) );
		root_child2.Style.SetPosition( Edge.Bottom, StyleLength.Percent( 10 ) );
		root_child2.Style.Width = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 90, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 160, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 90, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 90, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 90, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 90, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 160, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void absolute_layout_in_wrap_reverse_column_container()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexWrap = Wrap.WrapReverse;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 20 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_in_wrap_reverse_row_container()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexWrap = Wrap.WrapReverse;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 20 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_in_wrap_reverse_column_container_flex_end()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexWrap = Wrap.WrapReverse;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.AlignSelf = Align.FlexEnd;
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 20 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_in_wrap_reverse_row_container_flex_end()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.FlexWrap = Wrap.WrapReverse;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.AlignSelf = Align.FlexEnd;
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 20 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percent_absolute_position_infinite_height()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 300 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Points( 300 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.PositionType = PositionType.Absolute;
		root_child1.Style.SetPosition( Edge.Left, StyleLength.Percent( 20 ) );
		root_child1.Style.SetPosition( Edge.Top, StyleLength.Percent( 20 ) );
		root_child1.Style.Width = StyleLength.Percent( 20 );
		root_child1.Style.Height = StyleLength.Percent( 20 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 300, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 300, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 60, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 300, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 300, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 60, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void absolute_layout_percentage_height_based_on_padded_parent()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.SetBorder( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 100 );
		root_child0.Style.Height = StyleLength.Percent( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 45, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 45, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_percentage_height_based_on_padded_parent_and_align_items_center()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.AlignItems = Align.Center;
		root.Style.SetPadding( Edge.Top, StyleLength.Points( 20 ) );
		root.Style.SetPadding( Edge.Bottom, StyleLength.Points( 20 ) );
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 100 );
		root_child0.Style.Height = StyleLength.Percent( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_padding_left()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Left, StyleLength.Points( 100 ) );
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 150, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_padding_right()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Right, StyleLength.Points( 100 ) );
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_padding_top()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Top, StyleLength.Points( 100 ) );
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 150, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_padding_bottom()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Bottom, StyleLength.Points( 100 ) );
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 150, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_padding()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;

		var root_child0 = CreateNode();
		root_child0.Style.SetMargin( Edge.Left, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Right, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 200 );
		root_child0.Style.Height = StyleLength.Points( 200 );
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.PositionType = PositionType.Static;
		root_child0_child0.Style.SetPadding( Edge.Left, StyleLength.Points( 50 ) );
		root_child0_child0.Style.SetPadding( Edge.Top, StyleLength.Points( 50 ) );
		root_child0_child0.Style.SetPadding( Edge.Right, StyleLength.Points( 50 ) );
		root_child0_child0.Style.SetPadding( Edge.Bottom, StyleLength.Points( 50 ) );
		root_child0_child0.Style.Width = StyleLength.Points( 200 );
		root_child0_child0.Style.Height = StyleLength.Points( 200 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child0_child0 = CreateNode();
		root_child0_child0_child0.Style.PositionType = PositionType.Absolute;
		root_child0_child0_child0.Style.Width = StyleLength.Points( 50 );
		root_child0_child0_child0.Style.Height = StyleLength.Points( 50 );
		root_child0_child0.InsertChild( root_child0_child0_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 220, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 220, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 220, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 220, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_border()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;

		var root_child0 = CreateNode();
		root_child0.Style.SetMargin( Edge.Left, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Right, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 200 );
		root_child0.Style.Height = StyleLength.Points( 200 );
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.PositionType = PositionType.Static;
		root_child0_child0.Style.SetBorder( Edge.Left, StyleLength.Points( 10 ) );
		root_child0_child0.Style.SetBorder( Edge.Top, StyleLength.Points( 10 ) );
		root_child0_child0.Style.SetBorder( Edge.Right, StyleLength.Points( 10 ) );
		root_child0_child0.Style.SetBorder( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0_child0.Style.Width = StyleLength.Points( 200 );
		root_child0_child0.Style.Height = StyleLength.Points( 200 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child0_child0 = CreateNode();
		root_child0_child0_child0.Style.PositionType = PositionType.Absolute;
		root_child0_child0_child0.Style.Width = StyleLength.Points( 50 );
		root_child0_child0_child0.Style.Height = StyleLength.Points( 50 );
		root_child0_child0.InsertChild( root_child0_child0_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 220, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 220, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 220, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 220, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 140, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );
	}

	[TestMethod]
	public void absolute_layout_column_reverse_margin_border()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.ColumnReverse;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Points( 5 ) );
		root_child0.Style.SetPosition( Edge.Right, StyleLength.Points( 3 ) );
		root_child0.Style.SetMargin( Edge.Left, StyleLength.Points( 3 ) );
		root_child0.Style.SetMargin( Edge.Right, StyleLength.Points( 4 ) );
		root_child0.Style.SetBorder( Edge.Left, StyleLength.Points( 1 ) );
		root_child0.Style.SetBorder( Edge.Right, StyleLength.Points( 7 ) );
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 8, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 143, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

}
