// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGAndroidNewsFeed.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGAndroidNewsFeed.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class AndroidNewsFeedTest : FlexFixtureBase
{
	[TestMethod]
	public void android_news_feed()
	{
		var root = CreateNode();
		root.Style.AlignContent = Align.Stretch;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 1080 );

		var root_child0 = CreateNode();
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.AlignContent = Align.Stretch;
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child0_child0 = CreateNode();
		root_child0_child0_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0.InsertChild( root_child0_child0_child0, 0 );

		var root_child0_child0_child0_child0 = CreateNode();
		root_child0_child0_child0_child0.Style.FlexDirection = FlexDirection.Row;
		root_child0_child0_child0_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0_child0_child0.Style.AlignItems = Align.FlexStart;
		root_child0_child0_child0_child0.Style.SetMargin( Edge.Start, StyleLength.Points( 36 ) );
		root_child0_child0_child0_child0.Style.SetMargin( Edge.Top, StyleLength.Points( 24 ) );
		root_child0_child0_child0.InsertChild( root_child0_child0_child0_child0, 0 );

		var root_child0_child0_child0_child0_child0 = CreateNode();
		root_child0_child0_child0_child0_child0.Style.FlexDirection = FlexDirection.Row;
		root_child0_child0_child0_child0_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0_child0_child0.InsertChild( root_child0_child0_child0_child0_child0, 0 );

		var root_child0_child0_child0_child0_child0_child0 = CreateNode();
		root_child0_child0_child0_child0_child0_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0_child0_child0_child0_child0.Style.Width = StyleLength.Points( 120 );
		root_child0_child0_child0_child0_child0_child0.Style.Height = StyleLength.Points( 120 );
		root_child0_child0_child0_child0_child0.InsertChild( root_child0_child0_child0_child0_child0_child0, 0 );

		var root_child0_child0_child0_child0_child1 = CreateNode();
		root_child0_child0_child0_child0_child1.Style.AlignContent = Align.Stretch;
		root_child0_child0_child0_child0_child1.Style.FlexShrink = 1;
		root_child0_child0_child0_child0_child1.Style.SetMargin( Edge.Right, StyleLength.Points( 36 ) );
		root_child0_child0_child0_child0_child1.Style.SetPadding( Edge.Left, StyleLength.Points( 36 ) );
		root_child0_child0_child0_child0_child1.Style.SetPadding( Edge.Top, StyleLength.Points( 21 ) );
		root_child0_child0_child0_child0_child1.Style.SetPadding( Edge.Right, StyleLength.Points( 36 ) );
		root_child0_child0_child0_child0_child1.Style.SetPadding( Edge.Bottom, StyleLength.Points( 18 ) );
		root_child0_child0_child0_child0.InsertChild( root_child0_child0_child0_child0_child1, 1 );

		var root_child0_child0_child0_child0_child1_child0 = CreateNode();
		root_child0_child0_child0_child0_child1_child0.Style.FlexDirection = FlexDirection.Row;
		root_child0_child0_child0_child0_child1_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0_child0_child0_child1_child0.Style.FlexShrink = 1;
		root_child0_child0_child0_child0_child1.InsertChild( root_child0_child0_child0_child0_child1_child0, 0 );

		var root_child0_child0_child0_child0_child1_child1 = CreateNode();
		root_child0_child0_child0_child0_child1_child1.Style.AlignContent = Align.Stretch;
		root_child0_child0_child0_child0_child1_child1.Style.FlexShrink = 1;
		root_child0_child0_child0_child0_child1.InsertChild( root_child0_child0_child0_child0_child1_child1, 1 );

		var root_child0_child0_child1 = CreateNode();
		root_child0_child0_child1.Style.AlignContent = Align.Stretch;
		root_child0_child0.InsertChild( root_child0_child0_child1, 1 );

		var root_child0_child0_child1_child0 = CreateNode();
		root_child0_child0_child1_child0.Style.FlexDirection = FlexDirection.Row;
		root_child0_child0_child1_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0_child1_child0.Style.AlignItems = Align.FlexStart;
		root_child0_child0_child1_child0.Style.SetMargin( Edge.Start, StyleLength.Points( 174 ) );
		root_child0_child0_child1_child0.Style.SetMargin( Edge.Top, StyleLength.Points( 24 ) );
		root_child0_child0_child1.InsertChild( root_child0_child0_child1_child0, 0 );

		var root_child0_child0_child1_child0_child0 = CreateNode();
		root_child0_child0_child1_child0_child0.Style.FlexDirection = FlexDirection.Row;
		root_child0_child0_child1_child0_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0_child1_child0.InsertChild( root_child0_child0_child1_child0_child0, 0 );

		var root_child0_child0_child1_child0_child0_child0 = CreateNode();
		root_child0_child0_child1_child0_child0_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0_child1_child0_child0_child0.Style.Width = StyleLength.Points( 72 );
		root_child0_child0_child1_child0_child0_child0.Style.Height = StyleLength.Points( 72 );
		root_child0_child0_child1_child0_child0.InsertChild( root_child0_child0_child1_child0_child0_child0, 0 );

		var root_child0_child0_child1_child0_child1 = CreateNode();
		root_child0_child0_child1_child0_child1.Style.AlignContent = Align.Stretch;
		root_child0_child0_child1_child0_child1.Style.FlexShrink = 1;
		root_child0_child0_child1_child0_child1.Style.SetMargin( Edge.Right, StyleLength.Points( 36 ) );
		root_child0_child0_child1_child0_child1.Style.SetPadding( Edge.Left, StyleLength.Points( 36 ) );
		root_child0_child0_child1_child0_child1.Style.SetPadding( Edge.Top, StyleLength.Points( 21 ) );
		root_child0_child0_child1_child0_child1.Style.SetPadding( Edge.Right, StyleLength.Points( 36 ) );
		root_child0_child0_child1_child0_child1.Style.SetPadding( Edge.Bottom, StyleLength.Points( 18 ) );
		root_child0_child0_child1_child0.InsertChild( root_child0_child0_child1_child0_child1, 1 );

		var root_child0_child0_child1_child0_child1_child0 = CreateNode();
		root_child0_child0_child1_child0_child1_child0.Style.FlexDirection = FlexDirection.Row;
		root_child0_child0_child1_child0_child1_child0.Style.AlignContent = Align.Stretch;
		root_child0_child0_child1_child0_child1_child0.Style.FlexShrink = 1;
		root_child0_child0_child1_child0_child1.InsertChild( root_child0_child0_child1_child0_child1_child0, 0 );

		var root_child0_child0_child1_child0_child1_child1 = CreateNode();
		root_child0_child0_child1_child0_child1_child1.Style.AlignContent = Align.Stretch;
		root_child0_child0_child1_child0_child1_child1.Style.FlexShrink = 1;
		root_child0_child0_child1_child0_child1.InsertChild( root_child0_child0_child1_child0_child1_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 240, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 240, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 240, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 144, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child0_child0, true ).Left, "root_child0_child0_child0_child0.Left" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child0_child0_child0_child0, true ).Top, "root_child0_child0_child0_child0.Top" );
		AssertEq( 1044, FixtureGeometry.GetRect( root_child0_child0_child0_child0, true ).Width, "root_child0_child0_child0_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0, true ).Height, "root_child0_child0_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0, true ).Left, "root_child0_child0_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0, true ).Top, "root_child0_child0_child0_child0_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0, true ).Width, "root_child0_child0_child0_child0_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0, true ).Height, "root_child0_child0_child0_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0_child0, true ).Left, "root_child0_child0_child0_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0_child0, true ).Top, "root_child0_child0_child0_child0_child0_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0_child0, true ).Width, "root_child0_child0_child0_child0_child0_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0_child0, true ).Height, "root_child0_child0_child0_child0_child0_child0.Height" );

		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1, true ).Left, "root_child0_child0_child0_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1, true ).Top, "root_child0_child0_child0_child0_child1.Top" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1, true ).Width, "root_child0_child0_child0_child0_child1.Width" );
		AssertEq( 39, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1, true ).Height, "root_child0_child0_child0_child0_child1.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child0, true ).Left, "root_child0_child0_child0_child0_child1_child0.Left" );
		AssertEq( 21, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child0, true ).Top, "root_child0_child0_child0_child0_child1_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child0, true ).Width, "root_child0_child0_child0_child0_child1_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child0, true ).Height, "root_child0_child0_child0_child0_child1_child0.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child1, true ).Left, "root_child0_child0_child0_child0_child1_child1.Left" );
		AssertEq( 21, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child1, true ).Top, "root_child0_child0_child0_child0_child1_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child1, true ).Width, "root_child0_child0_child0_child0_child1_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child1, true ).Height, "root_child0_child0_child0_child0_child1_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Left, "root_child0_child0_child1.Left" );
		AssertEq( 144, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Top, "root_child0_child0_child1.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Width, "root_child0_child0_child1.Width" );
		AssertEq( 96, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Height, "root_child0_child0_child1.Height" );

		AssertEq( 174, FixtureGeometry.GetRect( root_child0_child0_child1_child0, true ).Left, "root_child0_child0_child1_child0.Left" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child0_child0_child1_child0, true ).Top, "root_child0_child0_child1_child0.Top" );
		AssertEq( 906, FixtureGeometry.GetRect( root_child0_child0_child1_child0, true ).Width, "root_child0_child0_child1_child0.Width" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0, true ).Height, "root_child0_child0_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0, true ).Left, "root_child0_child0_child1_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0, true ).Top, "root_child0_child0_child1_child0_child0.Top" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0, true ).Width, "root_child0_child0_child1_child0_child0.Width" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0, true ).Height, "root_child0_child0_child1_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0_child0, true ).Left, "root_child0_child0_child1_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0_child0, true ).Top, "root_child0_child0_child1_child0_child0_child0.Top" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0_child0, true ).Width, "root_child0_child0_child1_child0_child0_child0.Width" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0_child0, true ).Height, "root_child0_child0_child1_child0_child0_child0.Height" );

		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1, true ).Left, "root_child0_child0_child1_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1, true ).Top, "root_child0_child0_child1_child0_child1.Top" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1, true ).Width, "root_child0_child0_child1_child0_child1.Width" );
		AssertEq( 39, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1, true ).Height, "root_child0_child0_child1_child0_child1.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child0, true ).Left, "root_child0_child0_child1_child0_child1_child0.Left" );
		AssertEq( 21, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child0, true ).Top, "root_child0_child0_child1_child0_child1_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child0, true ).Width, "root_child0_child0_child1_child0_child1_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child0, true ).Height, "root_child0_child0_child1_child0_child1_child0.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child1, true ).Left, "root_child0_child0_child1_child0_child1_child1.Left" );
		AssertEq( 21, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child1, true ).Top, "root_child0_child0_child1_child0_child1_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child1, true ).Width, "root_child0_child0_child1_child0_child1_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child1, true ).Height, "root_child0_child0_child1_child0_child1_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 240, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 240, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 240, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 144, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0, true ).Left, "root_child0_child0_child0_child0.Left" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child0_child0_child0_child0, true ).Top, "root_child0_child0_child0_child0.Top" );
		AssertEq( 1044, FixtureGeometry.GetRect( root_child0_child0_child0_child0, true ).Width, "root_child0_child0_child0_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0, true ).Height, "root_child0_child0_child0_child0.Height" );

		AssertEq( 924, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0, true ).Left, "root_child0_child0_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0, true ).Top, "root_child0_child0_child0_child0_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0, true ).Width, "root_child0_child0_child0_child0_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0, true ).Height, "root_child0_child0_child0_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0_child0, true ).Left, "root_child0_child0_child0_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0_child0, true ).Top, "root_child0_child0_child0_child0_child0_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0_child0, true ).Width, "root_child0_child0_child0_child0_child0_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child0_child0, true ).Height, "root_child0_child0_child0_child0_child0_child0.Height" );

		AssertEq( 816, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1, true ).Left, "root_child0_child0_child0_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1, true ).Top, "root_child0_child0_child0_child0_child1.Top" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1, true ).Width, "root_child0_child0_child0_child0_child1.Width" );
		AssertEq( 39, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1, true ).Height, "root_child0_child0_child0_child0_child1.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child0, true ).Left, "root_child0_child0_child0_child0_child1_child0.Left" );
		AssertEq( 21, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child0, true ).Top, "root_child0_child0_child0_child0_child1_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child0, true ).Width, "root_child0_child0_child0_child0_child1_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child0, true ).Height, "root_child0_child0_child0_child0_child1_child0.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child1, true ).Left, "root_child0_child0_child0_child0_child1_child1.Left" );
		AssertEq( 21, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child1, true ).Top, "root_child0_child0_child0_child0_child1_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child1, true ).Width, "root_child0_child0_child0_child0_child1_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0_child0_child1_child1, true ).Height, "root_child0_child0_child0_child0_child1_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Left, "root_child0_child0_child1.Left" );
		AssertEq( 144, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Top, "root_child0_child0_child1.Top" );
		AssertEq( 1080, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Width, "root_child0_child0_child1.Width" );
		AssertEq( 96, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Height, "root_child0_child0_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0, true ).Left, "root_child0_child0_child1_child0.Left" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child0_child0_child1_child0, true ).Top, "root_child0_child0_child1_child0.Top" );
		AssertEq( 906, FixtureGeometry.GetRect( root_child0_child0_child1_child0, true ).Width, "root_child0_child0_child1_child0.Width" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0, true ).Height, "root_child0_child0_child1_child0.Height" );

		AssertEq( 834, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0, true ).Left, "root_child0_child0_child1_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0, true ).Top, "root_child0_child0_child1_child0_child0.Top" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0, true ).Width, "root_child0_child0_child1_child0_child0.Width" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0, true ).Height, "root_child0_child0_child1_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0_child0, true ).Left, "root_child0_child0_child1_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0_child0, true ).Top, "root_child0_child0_child1_child0_child0_child0.Top" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0_child0, true ).Width, "root_child0_child0_child1_child0_child0_child0.Width" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child0_child0, true ).Height, "root_child0_child0_child1_child0_child0_child0.Height" );

		AssertEq( 726, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1, true ).Left, "root_child0_child0_child1_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1, true ).Top, "root_child0_child0_child1_child0_child1.Top" );
		AssertEq( 72, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1, true ).Width, "root_child0_child0_child1_child0_child1.Width" );
		AssertEq( 39, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1, true ).Height, "root_child0_child0_child1_child0_child1.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child0, true ).Left, "root_child0_child0_child1_child0_child1_child0.Left" );
		AssertEq( 21, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child0, true ).Top, "root_child0_child0_child1_child0_child1_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child0, true ).Width, "root_child0_child0_child1_child0_child1_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child0, true ).Height, "root_child0_child0_child1_child0_child1_child0.Height" );

		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child1, true ).Left, "root_child0_child0_child1_child0_child1_child1.Left" );
		AssertEq( 21, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child1, true ).Top, "root_child0_child0_child1_child0_child1_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child1, true ).Width, "root_child0_child0_child1_child0_child1_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1_child0_child1_child1, true ).Height, "root_child0_child0_child1_child0_child1_child1.Height" );
	}

}
