// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGDimensionTest.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGDimensionTest.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class DimensionTest : FlexFixtureBase
{
	[TestMethod]
	public void wrap_child()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Points( 100 );
		root_child0.Style.Height = StyleLength.Points( 100 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void wrap_grandchild()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;

		var root_child0 = CreateNode();
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.Width = StyleLength.Points( 100 );
		root_child0_child0.Style.Height = StyleLength.Points( 100 );
		root_child0.InsertChild( root_child0_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );
	}

}
