// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGDisplayContentsTest.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGDisplayContentsTest.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class DisplayContentsTest : FlexFixtureBase
{
	[TestMethod]
	public void test1()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.Display = Display.Contents;
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexGrow = 1;
		root_child0_child0.Style.FlexShrink = 1;
		root_child0_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child1 = CreateNode();
		root_child0_child1.Style.FlexGrow = 1;
		root_child0_child1.Style.FlexShrink = 1;
		root_child0_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child1.Style.Height = StyleLength.Points( 20 );
		root_child0.InsertChild( root_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );
	}

}
