// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGDisplayTest.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGDisplayTest.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class DisplayTest : FlexFixtureBase
{
	[TestMethod]
	public void display_none()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Display = Display.None;
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void display_none_fixed_size()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.Width = StyleLength.Points( 20 );
		root_child1.Style.Height = StyleLength.Points( 20 );
		root_child1.Style.Display = Display.None;
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void display_none_with_margin()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.SetMargin( Edge.Left, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Right, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 20 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root_child0.Style.Display = Display.None;
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void display_none_with_child()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexShrink = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.FlexShrink = 1;
		root_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child1.Style.Display = Display.None;
		root.InsertChild( root_child1, 1 );

		var root_child1_child0 = CreateNode();
		root_child1_child0.Style.FlexGrow = 1;
		root_child1_child0.Style.FlexShrink = 1;
		root_child1_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child1_child0.Style.Width = StyleLength.Points( 20 );
		root_child1.InsertChild( root_child1_child0, 0 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.FlexShrink = 1;
		root_child2.Style.FlexBasis = StyleLength.Percent( 0 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void display_none_with_position()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.SetPosition( Edge.Top, StyleLength.Points( 10 ) );
		root_child1.Style.Display = Display.None;
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void display_none_with_position_absolute()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 100 );
		root_child0.Style.Height = StyleLength.Points( 100 );
		root_child0.Style.Display = Display.None;
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void display_contents()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.Display = Display.Contents;
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexGrow = 1;
		root_child0_child0.Style.FlexShrink = 1;
		root_child0_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child1 = CreateNode();
		root_child0_child1.Style.FlexGrow = 1;
		root_child0_child1.Style.FlexShrink = 1;
		root_child0_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child1.Style.Height = StyleLength.Points( 20 );
		root_child0.InsertChild( root_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );
	}

	[TestMethod]
	public void display_contents_fixed_size()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root_child0.Style.Display = Display.Contents;
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexGrow = 1;
		root_child0_child0.Style.FlexShrink = 1;
		root_child0_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child1 = CreateNode();
		root_child0_child1.Style.FlexGrow = 1;
		root_child0_child1.Style.FlexShrink = 1;
		root_child0_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child1.Style.Height = StyleLength.Points( 20 );
		root_child0.InsertChild( root_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );
	}

	[TestMethod]
	public void display_contents_with_margin()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.SetMargin( Edge.Left, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Right, StyleLength.Points( 10 ) );
		root_child0.Style.SetMargin( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 20 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root_child0.Style.Display = Display.Contents;
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void display_contents_with_padding()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.SetPadding( Edge.Left, StyleLength.Points( 10 ) );
		root_child0.Style.SetPadding( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.SetPadding( Edge.Right, StyleLength.Points( 10 ) );
		root_child0.Style.SetPadding( Edge.Bottom, StyleLength.Points( 10 ) );
		root_child0.Style.Display = Display.Contents;
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexGrow = 1;
		root_child0_child0.Style.FlexShrink = 1;
		root_child0_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child1 = CreateNode();
		root_child0_child1.Style.FlexGrow = 1;
		root_child0_child1.Style.FlexShrink = 1;
		root_child0_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child1.Style.Height = StyleLength.Points( 20 );
		root_child0.InsertChild( root_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );
	}

	[TestMethod]
	public void display_contents_with_position()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Points( 10 ) );
		root_child0.Style.Display = Display.Contents;
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexGrow = 1;
		root_child0_child0.Style.FlexShrink = 1;
		root_child0_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child1 = CreateNode();
		root_child0_child1.Style.FlexGrow = 1;
		root_child0_child1.Style.FlexShrink = 1;
		root_child0_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child1.Style.Height = StyleLength.Points( 20 );
		root_child0.InsertChild( root_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );
	}

	[TestMethod]
	public void display_contents_with_position_absolute()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root_child0.Style.Display = Display.Contents;
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexGrow = 1;
		root_child0_child0.Style.FlexShrink = 1;
		root_child0_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child1 = CreateNode();
		root_child0_child1.Style.FlexGrow = 1;
		root_child0_child1.Style.FlexShrink = 1;
		root_child0_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child1.Style.Height = StyleLength.Points( 20 );
		root_child0.InsertChild( root_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );
	}

	[TestMethod]
	public void display_contents_nested()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.Display = Display.Contents;
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.Display = Display.Contents;
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child0_child0 = CreateNode();
		root_child0_child0_child0.Style.FlexGrow = 1;
		root_child0_child0_child0.Style.FlexShrink = 1;
		root_child0_child0_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0_child0.InsertChild( root_child0_child0_child0, 0 );

		var root_child0_child0_child1 = CreateNode();
		root_child0_child0_child1.Style.FlexGrow = 1;
		root_child0_child0_child1.Style.FlexShrink = 1;
		root_child0_child0_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0_child0_child1.Style.Height = StyleLength.Points( 20 );
		root_child0_child0.InsertChild( root_child0_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Left, "root_child0_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Top, "root_child0_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Width, "root_child0_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Height, "root_child0_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Left, "root_child0_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Top, "root_child0_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Width, "root_child0_child0_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Height, "root_child0_child0_child1.Height" );
	}

	[TestMethod]
	public void display_contents_with_siblings()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexShrink = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child0.Style.Height = StyleLength.Points( 30 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.Display = Display.Contents;
		root.InsertChild( root_child1, 1 );

		var root_child1_child0 = CreateNode();
		root_child1_child0.Style.FlexGrow = 1;
		root_child1_child0.Style.FlexShrink = 1;
		root_child1_child0.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child1_child0.Style.Height = StyleLength.Points( 10 );
		root_child1.InsertChild( root_child1_child0, 0 );

		var root_child1_child1 = CreateNode();
		root_child1_child1.Style.FlexGrow = 1;
		root_child1_child1.Style.FlexShrink = 1;
		root_child1_child1.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child1_child1.Style.Height = StyleLength.Points( 20 );
		root_child1.InsertChild( root_child1_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.FlexShrink = 1;
		root_child2.Style.FlexBasis = StyleLength.Percent( 0 );
		root_child2.Style.Height = StyleLength.Points( 30 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child1_child1, true ).Left, "root_child1_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child1, true ).Top, "root_child1_child1.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1_child1, true ).Width, "root_child1_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child1_child1, true ).Height, "root_child1_child1.Height" );

		AssertEq( 75, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child1_child1, true ).Left, "root_child1_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child1, true ).Top, "root_child1_child1.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1_child1, true ).Width, "root_child1_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child1_child1, true ).Height, "root_child1_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

}
