// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGFlexTest.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGFlexTest.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class FlexTest : FlexFixtureBase
{
	[TestMethod]
	public void flex_basis_flex_grow_column()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void flex_shrink_flex_grow_row()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 500 );
		root.Style.Height = StyleLength.Points( 500 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexShrink = 1;
		root_child0.Style.Width = StyleLength.Points( 500 );
		root_child0.Style.Height = StyleLength.Points( 100 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexShrink = 1;
		root_child1.Style.Width = StyleLength.Points( 500 );
		root_child1.Style.Height = StyleLength.Points( 100 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 250, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 250, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 250, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 250, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 250, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 250, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void flex_shrink_flex_grow_child_flex_shrink_other_child()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 500 );
		root.Style.Height = StyleLength.Points( 500 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexShrink = 1;
		root_child0.Style.Width = StyleLength.Points( 500 );
		root_child0.Style.Height = StyleLength.Points( 100 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.FlexShrink = 1;
		root_child1.Style.Width = StyleLength.Points( 500 );
		root_child1.Style.Height = StyleLength.Points( 100 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 250, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 250, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 250, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 250, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 250, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 250, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void flex_basis_flex_grow_row()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 75, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void flex_basis_flex_shrink_column()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexShrink = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 100 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexBasis = StyleLength.Points( 50 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void flex_basis_flex_shrink_row()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexShrink = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 100 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexBasis = StyleLength.Points( 50 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void flex_shrink_to_zero()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Height = StyleLength.Points( 75 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexShrink = 1;
		root_child1.Style.Width = StyleLength.Points( 50 );
		root_child1.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.Width = StyleLength.Points( 50 );
		root_child2.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 75, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 75, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void flex_basis_overrides_main_size()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void flex_grow_shrink_at_most()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexGrow = 1;
		root_child0_child0.Style.FlexShrink = 1;
		root_child0.InsertChild( root_child0_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );
	}

	[TestMethod]
	public void flex_grow_less_than_factor_one()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 500 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 0.2f;
		root_child0.Style.FlexBasis = StyleLength.Points( 40 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 0.2f;
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 0.4f;
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 132, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 132, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 92, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 224, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 184, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 132, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 132, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 92, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 224, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 184, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

}
