// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGPaddingTest.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGPaddingTest.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class PaddingTest : FlexFixtureBase
{
	[TestMethod]
	public void padding_no_size()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Left, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Right, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Bottom, StyleLength.Points( 10 ) );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 20, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );
	}

	[TestMethod]
	public void padding_container_match_child()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Left, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Right, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Bottom, StyleLength.Points( 10 ) );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void padding_flex_child()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Left, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Right, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Bottom, StyleLength.Points( 10 ) );
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.Width = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void padding_stretch_child()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Left, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Top, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Right, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.Bottom, StyleLength.Points( 10 ) );
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void padding_center_child()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.AlignItems = Align.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Start, StyleLength.Points( 10 ) );
		root.Style.SetPadding( Edge.End, StyleLength.Points( 20 ) );
		root.Style.SetPadding( Edge.Bottom, StyleLength.Points( 20 ) );
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 35, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 35, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void child_with_padding_align_end()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.FlexEnd;
		root.Style.AlignItems = Align.FlexEnd;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.SetPadding( Edge.Left, StyleLength.Points( 20 ) );
		root_child0.Style.SetPadding( Edge.Top, StyleLength.Points( 20 ) );
		root_child0.Style.SetPadding( Edge.Right, StyleLength.Points( 20 ) );
		root_child0.Style.SetPadding( Edge.Bottom, StyleLength.Points( 20 ) );
		root_child0.Style.Width = StyleLength.Points( 100 );
		root_child0.Style.Height = StyleLength.Points( 100 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void physical_and_relative_edge_defined()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPadding( Edge.Left, StyleLength.Points( 20 ) );
		root.Style.SetPadding( Edge.End, StyleLength.Points( 50 ) );
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 100 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 130, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

}
