// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGPercentageTest.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGPercentageTest.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class PercentageTest : FlexFixtureBase
{
	[TestMethod]
	public void percentage_width_height()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 30 );
		root_child0.Style.Height = StyleLength.Percent( 30 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 140, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percentage_position_left_top()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 400 );
		root.Style.Height = StyleLength.Points( 400 );

		var root_child0 = CreateNode();
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Percent( 10 ) );
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Percent( 20 ) );
		root_child0.Style.Width = StyleLength.Percent( 45 );
		root_child0.Style.Height = StyleLength.Percent( 55 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 400, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 400, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 40, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 180, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 220, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 400, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 400, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 260, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 180, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 220, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percentage_position_bottom_right()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 500 );
		root.Style.Height = StyleLength.Points( 500 );

		var root_child0 = CreateNode();
		root_child0.Style.SetPosition( Edge.Right, StyleLength.Percent( 20 ) );
		root_child0.Style.SetPosition( Edge.Bottom, StyleLength.Percent( 10 ) );
		root_child0.Style.Width = StyleLength.Percent( 55 );
		root_child0.Style.Height = StyleLength.Percent( 15 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( -100, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( -50, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 275, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 500, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 125, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( -50, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 275, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percentage_flex_basis()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 50 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.FlexBasis = StyleLength.Percent( 25 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 125, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 125, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 125, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_flex_basis_cross()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 50 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.FlexBasis = StyleLength.Percent( 25 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 125, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 125, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 125, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 125, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	[Ignore( "Skipped upstream (GTEST_SKIP) - Chrome and upstream disagree here" )]
	public void percentage_flex_basis_cross_min_height()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.MinHeight = StyleLength.Percent( 60 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 2;
		root_child1.Style.MinHeight = StyleLength.Percent( 10 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_flex_basis_main_max_height()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child0.Style.MaxHeight = StyleLength.Percent( 60 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 4;
		root_child1.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child1.Style.MaxHeight = StyleLength.Percent( 20 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 52, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 52, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 148, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 148, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 52, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 148, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_flex_basis_cross_max_height()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child0.Style.MaxHeight = StyleLength.Percent( 60 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 4;
		root_child1.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child1.Style.MaxHeight = StyleLength.Percent( 20 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_flex_basis_main_max_width()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 15 );
		root_child0.Style.MaxWidth = StyleLength.Percent( 60 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 4;
		root_child1.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child1.Style.MaxWidth = StyleLength.Percent( 20 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 120, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_flex_basis_cross_max_width()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child0.Style.MaxWidth = StyleLength.Percent( 60 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 4;
		root_child1.Style.FlexBasis = StyleLength.Percent( 15 );
		root_child1.Style.MaxWidth = StyleLength.Percent( 20 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 160, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 40, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_flex_basis_main_min_width()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 15 );
		root_child0.Style.MinWidth = StyleLength.Percent( 60 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 4;
		root_child1.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child1.Style.MinWidth = StyleLength.Percent( 20 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 120, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 80, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 120, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 80, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_flex_basis_cross_min_width()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child0.Style.MinWidth = StyleLength.Percent( 60 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 4;
		root_child1.Style.FlexBasis = StyleLength.Percent( 15 );
		root_child1.Style.MinWidth = StyleLength.Percent( 20 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_multiple_nested_with_padding_margin_and_percentage_values()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Percent( 10 );
		root_child0.Style.SetMargin( Edge.Left, StyleLength.Points( 5 ) );
		root_child0.Style.SetMargin( Edge.Top, StyleLength.Points( 5 ) );
		root_child0.Style.SetMargin( Edge.Right, StyleLength.Points( 5 ) );
		root_child0.Style.SetMargin( Edge.Bottom, StyleLength.Points( 5 ) );
		root_child0.Style.SetPadding( Edge.Left, StyleLength.Points( 3 ) );
		root_child0.Style.SetPadding( Edge.Top, StyleLength.Points( 3 ) );
		root_child0.Style.SetPadding( Edge.Right, StyleLength.Points( 3 ) );
		root_child0.Style.SetPadding( Edge.Bottom, StyleLength.Points( 3 ) );
		root_child0.Style.MinWidth = StyleLength.Percent( 60 );
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.SetMargin( Edge.Left, StyleLength.Points( 5 ) );
		root_child0_child0.Style.SetMargin( Edge.Top, StyleLength.Points( 5 ) );
		root_child0_child0.Style.SetMargin( Edge.Right, StyleLength.Points( 5 ) );
		root_child0_child0.Style.SetMargin( Edge.Bottom, StyleLength.Points( 5 ) );
		root_child0_child0.Style.SetPadding( Edge.Left, StyleLength.Percent( 3 ) );
		root_child0_child0.Style.SetPadding( Edge.Top, StyleLength.Percent( 3 ) );
		root_child0_child0.Style.SetPadding( Edge.Right, StyleLength.Percent( 3 ) );
		root_child0_child0.Style.SetPadding( Edge.Bottom, StyleLength.Percent( 3 ) );
		root_child0_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child0_child0 = CreateNode();
		root_child0_child0_child0.Style.SetMargin( Edge.Left, StyleLength.Percent( 5 ) );
		root_child0_child0_child0.Style.SetMargin( Edge.Top, StyleLength.Percent( 5 ) );
		root_child0_child0_child0.Style.SetMargin( Edge.Right, StyleLength.Percent( 5 ) );
		root_child0_child0_child0.Style.SetMargin( Edge.Bottom, StyleLength.Percent( 5 ) );
		root_child0_child0_child0.Style.SetPadding( Edge.Left, StyleLength.Points( 3 ) );
		root_child0_child0_child0.Style.SetPadding( Edge.Top, StyleLength.Points( 3 ) );
		root_child0_child0_child0.Style.SetPadding( Edge.Right, StyleLength.Points( 3 ) );
		root_child0_child0_child0.Style.SetPadding( Edge.Bottom, StyleLength.Points( 3 ) );
		root_child0_child0_child0.Style.Width = StyleLength.Percent( 45 );
		root_child0_child0.InsertChild( root_child0_child0_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 4;
		root_child1.Style.FlexBasis = StyleLength.Percent( 15 );
		root_child1.Style.MinWidth = StyleLength.Percent( 20 );
		root.InsertChild( root_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 5, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 5, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 190, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 48, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 8, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 8, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 92, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 6, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 58, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 142, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 5, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 5, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 190, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 48, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 90, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 8, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 92, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 46, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 36, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 6, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 58, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 142, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );
	}

	[TestMethod]
	public void percentage_margin_should_calculate_based_only_on_width()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.SetMargin( Edge.Left, StyleLength.Percent( 10 ) );
		root_child0.Style.SetMargin( Edge.Top, StyleLength.Percent( 10 ) );
		root_child0.Style.SetMargin( Edge.Right, StyleLength.Percent( 10 ) );
		root_child0.Style.SetMargin( Edge.Bottom, StyleLength.Percent( 10 ) );
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.Width = StyleLength.Points( 10 );
		root_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0.InsertChild( root_child0_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 160, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 160, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 150, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );
	}

	[TestMethod]
	public void percentage_padding_should_calculate_based_only_on_width()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.SetPadding( Edge.Left, StyleLength.Percent( 10 ) );
		root_child0.Style.SetPadding( Edge.Top, StyleLength.Percent( 10 ) );
		root_child0.Style.SetPadding( Edge.Right, StyleLength.Percent( 10 ) );
		root_child0.Style.SetPadding( Edge.Bottom, StyleLength.Percent( 10 ) );
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.Width = StyleLength.Points( 10 );
		root_child0_child0.Style.Height = StyleLength.Points( 10 );
		root_child0.InsertChild( root_child0_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 170, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );
	}

	[TestMethod]
	public void percentage_absolute_position()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Percent( 30 ) );
		root_child0.Style.SetPosition( Edge.Top, StyleLength.Percent( 10 ) );
		root_child0.Style.Width = StyleLength.Points( 10 );
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percentage_width_height_undefined_parent_size()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Percent( 50 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percent_within_flex_grow()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 350 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Points( 100 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root.InsertChild( root_child1, 1 );

		var root_child1_child0 = CreateNode();
		root_child1_child0.Style.Width = StyleLength.Percent( 100 );
		root_child1.InsertChild( root_child1_child0, 0 );

		var root_child2 = CreateNode();
		root_child2.Style.Width = StyleLength.Points( 100 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 350, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 250, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 350, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 250, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 150, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void percentage_container_in_wrapping_container()
	{
		var root = CreateNode();
		root.Style.JustifyContent = Justify.Center;
		root.Style.AlignItems = Align.Center;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 200 );
		root.Style.Height = StyleLength.Points( 200 );

		var root_child0 = CreateNode();
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexDirection = FlexDirection.Row;
		root_child0_child0.Style.JustifyContent = Justify.Center;
		root_child0_child0.Style.Width = StyleLength.Percent( 100 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child0_child0 = CreateNode();
		root_child0_child0_child0.Style.Width = StyleLength.Points( 50 );
		root_child0_child0_child0.Style.Height = StyleLength.Points( 50 );
		root_child0_child0.InsertChild( root_child0_child0_child0, 0 );

		var root_child0_child0_child1 = CreateNode();
		root_child0_child0_child1.Style.Width = StyleLength.Points( 50 );
		root_child0_child0_child1.Style.Height = StyleLength.Points( 50 );
		root_child0_child0.InsertChild( root_child0_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Left, "root_child0_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Top, "root_child0_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Width, "root_child0_child0_child1.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Height, "root_child0_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 200, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 75, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Left, "root_child0_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Top, "root_child0_child0_child0.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Width, "root_child0_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child0, true ).Height, "root_child0_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Left, "root_child0_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Top, "root_child0_child0_child1.Top" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Width, "root_child0_child0_child1.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0_child1, true ).Height, "root_child0_child0_child1.Height" );
	}

	[TestMethod]
	public void percent_absolute_position()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexDirection = FlexDirection.Row;
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.SetPosition( Edge.Left, StyleLength.Percent( 50 ) );
		root_child0.Style.Width = StyleLength.Percent( 100 );
		root_child0.Style.Height = StyleLength.Points( 50 );
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.Width = StyleLength.Percent( 100 );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child1 = CreateNode();
		root_child0_child1.Style.Width = StyleLength.Percent( 100 );
		root_child0.InsertChild( root_child0_child1, 1 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 60, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( -60, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );
	}

	[TestMethod]
	public void percent_of_minmax_main()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MinWidth = StyleLength.Points( 60 );
		root.Style.MaxWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	[Ignore( "Skipped upstream (GTEST_SKIP) - Chrome and upstream disagree here" )]
	public void percent_of_min_main()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MinWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	[Ignore( "Skipped upstream (GTEST_SKIP) - Chrome and upstream disagree here" )]
	public void percent_of_min_main_multiple()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MinWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.Width = StyleLength.Percent( 50 );
		root_child1.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.Width = StyleLength.Percent( 50 );
		root_child2.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 60, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( -30, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	[Ignore( "Skipped upstream (GTEST_SKIP) - Chrome and upstream disagree here" )]
	public void percent_of_max_main()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MaxWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percent_of_minmax_cross_stretched()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MinWidth = StyleLength.Points( 60 );
		root.Style.MaxWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percent_absolute_of_minmax_cross_stretched()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MinWidth = StyleLength.Points( 60 );
		root.Style.MaxWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.PositionType = PositionType.Absolute;
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percent_of_minmax_cross_unstretched()
	{
		var root = CreateNode();
		root.Style.AlignItems = Align.FlexStart;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MinWidth = StyleLength.Points( 60 );
		root.Style.MaxWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	[Ignore( "Skipped upstream (GTEST_SKIP) - Chrome and upstream disagree here" )]
	public void percent_of_min_cross_unstretched()
	{
		var root = CreateNode();
		root.Style.AlignItems = Align.FlexStart;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MinWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 60, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

	[TestMethod]
	public void percent_of_max_cross_unstretched()
	{
		var root = CreateNode();
		root.Style.AlignItems = Align.FlexStart;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.MaxWidth = StyleLength.Points( 60 );
		root.Style.Height = StyleLength.Points( 50 );

		var root_child0 = CreateNode();
		root_child0.Style.Width = StyleLength.Percent( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 50, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 20, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );
	}

}
