// <auto-generated>
// Ported from Yoga's Chrome-generated conformance fixtures (YGRoundingTest.cpp), MIT licensed
// (Copyright (c) Meta Platforms, Inc. and affiliates). Regenerate with convert_flex_fixtures.py.
// Source: https://github.com/facebook/yoga/blob/v3.2.1/tests/generated/YGRoundingTest.cpp
// </auto-generated>
using Sandbox.Layout;

namespace LayoutTests.FlexConformance;

[TestClass]
public class RoundingTest : FlexFixtureBase
{
	[TestMethod]
	public void rounding_flex_basis_flex_grow_row_width_of_100()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 33, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 33, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 34, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 67, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 33, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 67, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 33, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 33, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 34, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 33, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_flex_basis_flex_grow_row_prime_number_width()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 113 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root.InsertChild( root_child2, 2 );

		var root_child3 = CreateNode();
		root_child3.Style.FlexGrow = 1;
		root.InsertChild( root_child3, 3 );

		var root_child4 = CreateNode();
		root_child4.Style.FlexGrow = 1;
		root.InsertChild( root_child4, 4 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 23, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 23, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 22, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 45, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 23, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		AssertEq( 68, FixtureGeometry.GetRect( root_child3, true ).Left, "root_child3.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child3, true ).Top, "root_child3.Top" );
		AssertEq( 22, FixtureGeometry.GetRect( root_child3, true ).Width, "root_child3.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child3, true ).Height, "root_child3.Height" );

		AssertEq( 90, FixtureGeometry.GetRect( root_child4, true ).Left, "root_child4.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child4, true ).Top, "root_child4.Top" );
		AssertEq( 23, FixtureGeometry.GetRect( root_child4, true ).Width, "root_child4.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child4, true ).Height, "root_child4.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 90, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 23, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 68, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 22, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 45, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 23, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		AssertEq( 23, FixtureGeometry.GetRect( root_child3, true ).Left, "root_child3.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child3, true ).Top, "root_child3.Top" );
		AssertEq( 22, FixtureGeometry.GetRect( root_child3, true ).Width, "root_child3.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child3, true ).Height, "root_child3.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child4, true ).Left, "root_child4.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child4, true ).Top, "root_child4.Top" );
		AssertEq( 23, FixtureGeometry.GetRect( root_child4, true ).Width, "root_child4.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child4, true ).Height, "root_child4.Height" );
	}

	[TestMethod]
	public void rounding_flex_basis_flex_shrink_row()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 101 );
		root.Style.Height = StyleLength.Points( 100 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexShrink = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 100 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexBasis = StyleLength.Points( 25 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexBasis = StyleLength.Points( 25 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 101, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 51, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 51, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 76, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 101, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 50, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 51, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_flex_basis_overrides_main_size()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 113 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_total_fractial()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 87.4f );
		root.Style.Height = StyleLength.Points( 113.4f );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 0.7f;
		root_child0.Style.FlexBasis = StyleLength.Points( 50.3f );
		root_child0.Style.Height = StyleLength.Points( 20.3f );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1.6f;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1.1f;
		root_child2.Style.Height = StyleLength.Points( 10.7f );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 59, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 59, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 59, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 59, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_total_fractial_nested()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 87.4f );
		root.Style.Height = StyleLength.Points( 113.4f );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 0.7f;
		root_child0.Style.FlexBasis = StyleLength.Points( 50.3f );
		root_child0.Style.Height = StyleLength.Points( 20.3f );
		root.InsertChild( root_child0, 0 );

		var root_child0_child0 = CreateNode();
		root_child0_child0.Style.FlexGrow = 1;
		root_child0_child0.Style.FlexBasis = StyleLength.Points( 0.3f );
		root_child0_child0.Style.SetPosition( Edge.Bottom, StyleLength.Points( 13.3f ) );
		root_child0_child0.Style.Height = StyleLength.Points( 9.9f );
		root_child0.InsertChild( root_child0_child0, 0 );

		var root_child0_child1 = CreateNode();
		root_child0_child1.Style.FlexGrow = 4;
		root_child0_child1.Style.FlexBasis = StyleLength.Points( 0.3f );
		root_child0_child1.Style.SetPosition( Edge.Top, StyleLength.Points( 13.3f ) );
		root_child0_child1.Style.Height = StyleLength.Points( 1.1f );
		root_child0.InsertChild( root_child0_child1, 1 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1.6f;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1.1f;
		root_child2.Style.Height = StyleLength.Points( 10.7f );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 59, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( -13, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 12, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 47, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 59, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 59, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child0, true ).Left, "root_child0_child0.Left" );
		AssertEq( -13, FixtureGeometry.GetRect( root_child0_child0, true ).Top, "root_child0_child0.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child0_child0, true ).Width, "root_child0_child0.Width" );
		AssertEq( 12, FixtureGeometry.GetRect( root_child0_child0, true ).Height, "root_child0_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0_child1, true ).Left, "root_child0_child1.Left" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child0_child1, true ).Top, "root_child0_child1.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child0_child1, true ).Width, "root_child0_child1.Width" );
		AssertEq( 47, FixtureGeometry.GetRect( root_child0_child1, true ).Height, "root_child0_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 59, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 30, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 87, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_fractial_input_1()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 113.4f );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_fractial_input_2()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 113.6f );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 114, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 65, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 65, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 114, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 65, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 65, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_fractial_input_3()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPosition( Edge.Top, StyleLength.Points( 0.3f ) );
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 113.4f );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 114, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 65, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 114, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 65, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_fractial_input_4()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.SetPosition( Edge.Top, StyleLength.Points( 0.7f ) );
		root.Style.Width = StyleLength.Points( 100 );
		root.Style.Height = StyleLength.Points( 113.4f );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.FlexBasis = StyleLength.Points( 50 );
		root_child0.Style.Height = StyleLength.Points( 20 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 1, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 1, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 113, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 64, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 25, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 89, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 100, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 24, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_inner_node_controversy_horizontal()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 320 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child1_child0 = CreateNode();
		root_child1_child0.Style.FlexGrow = 1;
		root_child1_child0.Style.Height = StyleLength.Points( 10 );
		root_child1.InsertChild( root_child1_child0, 0 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Height = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 320, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 107, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 213, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 320, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 213, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 107, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_inner_node_controversy_vertical()
	{
		var root = CreateNode();
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Height = StyleLength.Points( 320 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.Width = StyleLength.Points( 10 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Width = StyleLength.Points( 10 );
		root.InsertChild( root_child1, 1 );

		var root_child1_child0 = CreateNode();
		root_child1_child0.Style.FlexGrow = 1;
		root_child1_child0.Style.Width = StyleLength.Points( 10 );
		root_child1.InsertChild( root_child1_child0, 0 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Width = StyleLength.Points( 10 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 213, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 213, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 10, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

	[TestMethod]
	public void rounding_inner_node_controversy_combined()
	{
		var root = CreateNode();
		root.Style.FlexDirection = FlexDirection.Row;
		root.Style.PositionType = PositionType.Absolute;
		root.Style.Width = StyleLength.Points( 640 );
		root.Style.Height = StyleLength.Points( 320 );

		var root_child0 = CreateNode();
		root_child0.Style.FlexGrow = 1;
		root_child0.Style.Height = StyleLength.Percent( 100 );
		root.InsertChild( root_child0, 0 );

		var root_child1 = CreateNode();
		root_child1.Style.FlexGrow = 1;
		root_child1.Style.Height = StyleLength.Percent( 100 );
		root.InsertChild( root_child1, 1 );

		var root_child1_child0 = CreateNode();
		root_child1_child0.Style.FlexGrow = 1;
		root_child1_child0.Style.Width = StyleLength.Percent( 100 );
		root_child1.InsertChild( root_child1_child0, 0 );

		var root_child1_child1 = CreateNode();
		root_child1_child1.Style.FlexGrow = 1;
		root_child1_child1.Style.Width = StyleLength.Percent( 100 );
		root_child1.InsertChild( root_child1_child1, 1 );

		var root_child1_child1_child0 = CreateNode();
		root_child1_child1_child0.Style.FlexGrow = 1;
		root_child1_child1_child0.Style.Width = StyleLength.Percent( 100 );
		root_child1_child1.InsertChild( root_child1_child1_child0, 0 );

		var root_child1_child2 = CreateNode();
		root_child1_child2.Style.FlexGrow = 1;
		root_child1_child2.Style.Width = StyleLength.Percent( 100 );
		root_child1.InsertChild( root_child1_child2, 2 );

		var root_child2 = CreateNode();
		root_child2.Style.FlexGrow = 1;
		root_child2.Style.Height = StyleLength.Percent( 100 );
		root.InsertChild( root_child2, 2 );
		root.CalculateLayout( float.NaN, float.NaN, Direction.LTR );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 640, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 213, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 213, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child1, true ).Left, "root_child1_child1.Left" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child1_child1, true ).Top, "root_child1_child1.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1_child1, true ).Width, "root_child1_child1.Width" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1_child1, true ).Height, "root_child1_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child1_child0, true ).Left, "root_child1_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child1_child0, true ).Top, "root_child1_child1_child0.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1_child1_child0, true ).Width, "root_child1_child1_child0.Width" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1_child1_child0, true ).Height, "root_child1_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child2, true ).Left, "root_child1_child2.Left" );
		AssertEq( 213, FixtureGeometry.GetRect( root_child1_child2, true ).Top, "root_child1_child2.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1_child2, true ).Width, "root_child1_child2.Width" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child1_child2, true ).Height, "root_child1_child2.Height" );

		AssertEq( 427, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 213, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );

		root.CalculateLayout( float.NaN, float.NaN, Direction.RTL );

		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Left, "root.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root, true ).Top, "root.Top" );
		AssertEq( 640, FixtureGeometry.GetRect( root, true ).Width, "root.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root, true ).Height, "root.Height" );

		AssertEq( 427, FixtureGeometry.GetRect( root_child0, true ).Left, "root_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child0, true ).Top, "root_child0.Top" );
		AssertEq( 213, FixtureGeometry.GetRect( root_child0, true ).Width, "root_child0.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root_child0, true ).Height, "root_child0.Height" );

		AssertEq( 213, FixtureGeometry.GetRect( root_child1, true ).Left, "root_child1.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1, true ).Top, "root_child1.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1, true ).Width, "root_child1.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root_child1, true ).Height, "root_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Left, "root_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child0, true ).Top, "root_child1_child0.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1_child0, true ).Width, "root_child1_child0.Width" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child1_child0, true ).Height, "root_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child1, true ).Left, "root_child1_child1.Left" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child1_child1, true ).Top, "root_child1_child1.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1_child1, true ).Width, "root_child1_child1.Width" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1_child1, true ).Height, "root_child1_child1.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child1_child0, true ).Left, "root_child1_child1_child0.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child1_child0, true ).Top, "root_child1_child1_child0.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1_child1_child0, true ).Width, "root_child1_child1_child0.Width" );
		AssertEq( 106, FixtureGeometry.GetRect( root_child1_child1_child0, true ).Height, "root_child1_child1_child0.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child1_child2, true ).Left, "root_child1_child2.Left" );
		AssertEq( 213, FixtureGeometry.GetRect( root_child1_child2, true ).Top, "root_child1_child2.Top" );
		AssertEq( 214, FixtureGeometry.GetRect( root_child1_child2, true ).Width, "root_child1_child2.Width" );
		AssertEq( 107, FixtureGeometry.GetRect( root_child1_child2, true ).Height, "root_child1_child2.Height" );

		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Left, "root_child2.Left" );
		AssertEq( 0, FixtureGeometry.GetRect( root_child2, true ).Top, "root_child2.Top" );
		AssertEq( 213, FixtureGeometry.GetRect( root_child2, true ).Width, "root_child2.Width" );
		AssertEq( 320, FixtureGeometry.GetRect( root_child2, true ).Height, "root_child2.Height" );
	}

}
